server.port=8080

# Por padrão, a aplicação sobe em modo "dev"
spring.profiles.default=dev

# JWT
app.jwt.issuer=login-system
app.jwt.exp-minutes=60

# CORS (comma-separated). Use "*" apenas em dev.
app.cors.allowed-origins=*
