server.port=8080

# H2 IN-MEMORY
spring.datasource.url=jdbc:h2:mem:loginsystem;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# H2 console (dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT (HMAC)
app.jwt.secret=05664166737031497366352050321681
app.jwt.issuer=login-system
app.jwt.exp-minutes=60